# Use the official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the source code to the container
COPY real_time_chat.py /app/

# Install the required Python packages
RUN pip install flask-socketio eventlet
RUN pip install PyJWT
RUN pip install pymongo
RUN pip install pika

# Expose the port the application runs on
EXPOSE 5001

# Define the command to run the application
CMD ["python", "real_time_chat.py"]

